name: budgetbud
publish_to: 'none'
version: 1.0.3+11

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  collection: ^1.17.2
  easy_mask: ^2.0.1
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.1.1
  get_it: ^8.0.3
  intl: ^0.19.0
  json_annotation: ^4.8.1
  line_icons: ^2.0.3
  mobx: ^2.2.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^9.0.0
  json_serializable: ^6.7.1
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
