name: Firebase App Distribution

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build apk
        run: flutter build apk --profile

      - name: Distribute artifacts
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIALS }}
          groups: internal
          file: build/app/outputs/flutter-apk/app-profile.apk
          releaseNotes: ${{ github.event.head_commit.message }}